### ISSUE TITLE
Better error handling/instruction for otto commit

### ISSUE THREAD

**Issue by KyleVasulka** [chand1012/ottodocs#3]
When running otto commit the following error is returned:
![image](https://user-images.githubusercontent.com/16945872/234037119-e174c633-847b-4396-8c69-9dbb06515b97.png)

### Steps to reproduce:
- Download and extract windows binary from releases https://github.com/chand1012/ottodocs/releases/tag/v0.6.0

- run `otto commit`

This should instead tell me what I am doing wrong. I have noticed the same behavior if I run `otto commit -a`

**Comment by chand1012** [comment]
This seems to be a bug with the Crossbuild. This seems to be working when I build on Windows using the Windows version of go.

**Comment by chand1012** [comment]
> This seems to be a bug with the Crossbuild. This seems to be working when I build on Windows using the Windows version of go.

This is incorrect. Version downloaded from site works, however it could be a different version of Windows issue. I am on Windows 11, what are you on?

**Comment by KyleVasulka** [comment]
Windows 10. Good chance this is because the command was not run inside of a git repository. That should be reflected in the error code.

**Comment by chand1012** [comment]
Fixed in 5cc60e540192cc6b5455dc028c1b146f194c4c27. Will be present in next release.
