### ISSUE TITLE
otto chat may not be working

### ISSUE THREAD

**Issue by KyleVasulka** [chand1012/ottodocs#4]
I have tried several questions with `otto chat` after setting my openai key. 

It always says that it needs more information. Maybe this is because of the system prompt used in the chatgpt api?

![image](https://user-images.githubusercontent.com/16945872/234039451-7844e513-5e40-49c3-b64c-99fed72ea860.png)

**Comment by chand1012** [comment]
![image](https://user-images.githubusercontent.com/3521582/234058277-7cd786c9-fa4b-4c46-ad6d-8659825f6b8a.png)

Everything seems to be working on my end, which is strange. This is the version downloaded from GitHub releases. I am adding some more debugging options so we can see into the program further. I recommend cloning and attempting to build from source and seeing if the issue persists.

**Comment by Kyle-Vasulka** [comment]
Okay I have done more testing.

when using the `otto chat` command, even if you use "" to surround your query it still is only sending the first character/word. 

e.g.  "Why do people still make new programming languages" only sends `"` to openai

and

why do people still exist sends only `why` to openai

![image](https://user-images.githubusercontent.com/129444648/234105741-11f70e20-d9fe-45ff-bdb1-c0e1b01b2e3b.png)

I have also noticed that when passing -q if I don't surround what is next in quotes it only passes the first word and does not crash/warn me about the extra parameters

Maybe detect if more than 1 parameter is sent and warn the user that the question should be in quotes?

Also when using just plain auto chat, should take in entire phrase, not just first word/character

**Comment by KyleVasulka** [comment]
Okay I have done more testing.

when using the otto chat command, even if you use "" to surround your query it still is only sending the first character/word.

e.g. "Why do people still make new programming languages" only sends " to openai

and

why do people still exist sends only why to openai

![image](https://user-images.githubusercontent.com/16945872/234107578-9dbc1ceb-ea75-4aa7-bf58-209446a1fed3.png)


I have also noticed that when passing -q if I don't surround what is next in quotes it only passes the first word and does not crash/warn me about the extra parameters

Maybe detect if more than 1 parameter is sent and warn the user that the question should be in quotes?

Also when using just plain auto chat, should take in entire phrase, not just first word/character

**Comment by chand1012** [comment]
Can you try it using git bash? Either way this needs fixed but it will help
me understand what is going on.

**Comment by chand1012** [comment]
Fixed on main, will be in next release.
