### ISSUE TITLE
Completion command missing from Docs page

### ISSUE THREAD

**Issue by KyleVasulka** [chand1012/ottodocs#5]
![image](https://user-images.githubusercontent.com/16945872/234041474-f3f27df4-e039-4478-9c9c-031bbc041a59.png)
![image](https://user-images.githubusercontent.com/16945872/234041553-666a3dcd-2538-400b-b9ed-8e718d0315fb.png)

**Comment by chand1012** [comment]
Completion is auto generated by Cobra, I did not add it. Its missing from the [commands directory](https://meet.google.com/vcc-ipht-vvc). Not sure if I can have the docs auto generate it?

**Comment by chand1012** [comment]
This is automatically added by Cobra, not sure if I can add it to the docs generator. See the [commands dir](https://github.com/chand1012/ottodocs/tree/main/cmd).
